### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by oh-yu**

### CODE REVIEW

**Comment by hisasu00** [comment]
hoge

**Comment by oh-yu** [comment]
benchmarks.ipynb
- [x] gamma="auto", needs space before and after "equal"

**Comment by oh-yu** [comment]
get_x_y.py
- [x] Overall, argument and variable name "energy"(shape of (days,times) or (times, days)) should be named "energies". "energy"'(shape of (1,vals)) should be "energy" e.g. create_features(). Same logic applied to "occupancy".

※ below, follows functions in get_x_y_.py module
to_intervals_energy(energy, intervals)
- [x]  what is t?

to_intervals_occupancy(occupancy, intervals)
- [x] what is t?
- [x] occupancys => occupancies

get_targret_energy(house_id, target_months, interval_s)
- [x] interval_s => intervals

get_denominator(date, intervals, energy)
- [x] set default to argument intervals 
- [x] # maximum for 30 minutes before and after => 60 miniutes

build_ratio(date_columns, energy, intervals)
- [x] ratios={}, needs space before and after equation
- [x] set default to intervals

get_corresponding_energy()
- [x] energy_df => energies

get_weekdays(target_days)
- [x] weekdays => is_sunday(caller side should also follow this change)

get_am_pm(features)
- [x]  concatenation,drop should be out of this function's role
- [x] don't have to pass features to function, only features["Time"] should be enough

**Comment by oh-yu** [comment]
01-05.ipynb
- [x] arrange import order 
- [x] For the first execution, all function in get_x_y.py should be passed keyword args in all households.
- [x] As for “Lag＋1 Ratio” and “Lag-1 Ratio” , can code in the same way?

**Comment by oh-yu** [comment]
- [x] As for “Lag＋1 Ratio” and “Lag-1 Ratio” , no need np.array([0.5]), np.append(0.5, np.array([1,2,3])) is enough.

**Pull request merged**
